### ISSUE TITLE
seems to not work 

### ISSUE THREAD

**Issue by vicente-valls** [jacob-meacham/serverless-plugin-offline-kinesis-events#2]
Hi,

   I tried with serverless `1.25.0` or even with your example and it isnt working... :(

   Happy to help you if you need any info from my side.

**Comment by jacob-meacham** [comment]
Hi @vicente-valls what error do you see?

**Comment by vicente-valls** [comment]
@jacob-meacham , Plugin name for instance isnt valid on the example. I fixed that but still
not working, missing webpack.... You will see if you try to run it from the
scratch

**Comment by jacob-meacham** [comment]
@vicente-valls Sorry about that! This plugin was originally closed-source, and I didn't do a great job at moving it into open source. #3 is a PR that seems to fix the problems for me. I'll do a new release of the plugin once that merges, as well

**Comment by vicente-valls** [comment]
thanks a lot @jacob-meacham !

**Comment by jacob-meacham** [comment]
1.0.1 has been released (https://www.npmjs.com/package/serverless-plugin-offline-kinesis-events). Thanks for reporting!
